version: '3.3'

services:
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./htpasswd:/run/secrets/htpasswd
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
  node:
    image: node:12
    command: node /app/dist/index.js
    expose:
      - 80
    volumes:
      - ./app:/app
    networks:
      - net
    environment:
      DB_USER: user
      DB_PASS: 123
      DB_NAME: browser-tracker
  mongo:
    image: mongo:4
    volumes:
      - ./data:/data/db
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: browser-tracker
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    networks:
      - net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123

networks:
  net:
    driver: overlay
    attachable: true

