version: '3.3'

services:
  nginx:
    image: nginx:1.15
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
    secrets:
      - htpasswd
  node:
    image: chrisxf/browser-tracker:latest
    networks:
      - net
    environment:
      DB_USER_FILE: /run/secrets/db_user
      DB_PASS_FILE: /run/secrets/db_pass
      DB_NAME_FILE: /run/secrets/db_name
  mongo:
    image: mongo:4
    volumes:
      - ./data:/data/db
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_pass

secrets:
  htpasswd:
    file: secrets/htpasswd.txt
  db_name:
    file: secrets/db_name.txt
  db_user:
    file: secrets/db_user.txt
  db_pass:
    file: secrets/db_pass.txt

networks:
  net:
    driver: overlay
    attachable: true

